//Localhost
//Food

###Add a food item
POST http://localhost:3000/food
Content-Type: application/json

{
  "cat": "vegetable",
  "itemName": "celery",
  "stock": 0,
  "inCart": true
}

//Supplies
### Add a non-food item
POST http://localhost:3000/supplies
Content-Type: application/json

{
  "itemName": "pool hose",
  "stock": 0,
  "inCart": true,
  "color": "grey"
}

//Orders
### Add an order
POST http://localhost:3000/ordered
Content-Type: application/json

{
  "itemName": "goldfish crackers", 
  "quantityOrdered": 1,
  "color": "n/a",
  "dateOrdered": "09/12/22",
  "eta": "10/20/22",
  "price": 12,
  "gift": false
}

//Users
### Add a user
POST http://localhost:3000/users
Content-type: application/json

{
  "username": "kaisis",
  "email": "kaiconserve@wayuisland.com"
}