//Localhost
//Food

###Add a food item
POST http://localhost:3000/food
Content-Type: application/json

{
  "cat": "vegetable",
  "itemName": "carrots",
  "stock": 4,
  "inCart": false
}

//Supplies
### Add a non-food item
POST http://localhost:3000/supplies
Content-Type: application/json

{
  "itemName": "pencil",
  "stock": 5,
  "inCart": false,
  "color": "grey/black"
}

//Orders
### Add an order
POST http://localhost:3000/ordered
Content-Type: application/json

{
  "itemName": "water bottle lid", 
  "quantityOrdered": 2,
  "color": "pink",
  "dateOrdered": "10/15/22",
  "eta": "10/20/22",
  "price": 15,
  "gift": true
}