//Localhost
//Food

###Add a food item
POST http://localhost:3000/food
Content-Type: application/json

{
  "cat": "vegetable",
  "itemName": "carrots",
  "stock": 4,
  "inCart": false
}

//Supplies
### Add a non-food item
POST http://localhost:3000/supplies
Content-Type: application/json

{
  "itemName": "pencil",
  "stock": 5,
  "inCart": false,
  "color": "grey/black"
}