//ORDER TESTING
//Localhost

### Get all orders
GET http://localhost:3000/ordered

### Add an order
POST http://localhost:3000/ordered
Content-Type: application/json

{
  "itemName": "speaker", 
  "quantityOrdered": 2,
  "color": "black",
  "dateOrdered": "11/29/21",
  "eta": "12/14/21",
  "price": 250,
  "gift": true
}

### Get - dateOrdered
GET http://localhost:3000/ordered/dateOrdered/11

### Get - eta
GET http://localhost:3000/ordered/eta

### Get - id
GET http://localhost:3000/ordered/634f202e8844b094e6c0f4e0

### Update an Order
PUT http://localhost:3000/ordered/6350c5dd10cad1ebcc6e9af5
Content-Type: application/json

{
  "itemName": "speaker", 
  "quantityOrdered": 2,
  "color": "black",
  "dateOrdered": "11/29/21",
  "eta": "12/14/21",
  "price": 250,
  "gift": true
}

### Delete an Order
DELETE http://localhost:3000/ordered/63507e0bf59ff87a473b1549